./Vid2OpticalFlowCSV/sparse_flow -d /dev/null -c config.xml -o ../dataset/EgoOutside/csvs_32x32/running/Apoxee\ Wilderness\ Trail\ GoPro\ Trail\ Run\ \(Long\)-T3xBJ9XxTaA.csv -v ../dataset/EgoOutside/vids/running/Apoxee\ Wilderness\ Trail\ GoPro\ Trail\ Run\ \(Long\)-T3xBJ9XxTaA.mp4 &
./Vid2OpticalFlowCSV/sparse_flow -d /dev/null -c config.xml -o ../dataset/EgoOutside/csvs_32x32/running/Trail\ Run\ Boiling\ Springs\ Headcam\ POV-3X47KIfevx8.csv -v ../dataset/EgoOutside/vids/running/Trail\ Run\ Boiling\ Springs\ Headcam\ POV-3X47KIfevx8.mp4 &
./Vid2OpticalFlowCSV/sparse_flow -d /dev/null -c config.xml -o ../dataset/EgoOutside/csvs_32x32/running/helmet\ cam\ running\ barr\ trail-ZXgNHYaOLBk.csv -v ../dataset/EgoOutside/vids/running/helmet\ cam\ running\ barr\ trail-ZXgNHYaOLBk.mp4 &
./Vid2OpticalFlowCSV/sparse_flow -d /dev/null -c config.xml -o ../dataset/EgoOutside/csvs_32x32/running/Ayala\ Triangle\ Run\ with\ GoPro\ Hero\ 3+\ Black\ Edition-WbWnWojOtIs.csv -v ../dataset/EgoOutside/vids/running/Ayala\ Triangle\ Run\ with\ GoPro\ Hero\ 3+\ Black\ Edition-WbWnWojOtIs.mp4 &
./Vid2OpticalFlowCSV/sparse_flow -d /dev/null -c config.xml -o ../dataset/EgoOutside/csvs_32x32/running/GoPro\ HD\ Hero\ 2\ -\ Jogging-Odgf06c-TSk.csv -v ../dataset/EgoOutside/vids/running/GoPro\ HD\ Hero\ 2\ -\ Jogging-Odgf06c-TSk.mp4 &
./Vid2OpticalFlowCSV/sparse_flow -d /dev/null -c config.xml -o ../dataset/EgoOutside/csvs_32x32/running/Blackpool\ 10k\ fun\ run\ my\ \(pov\)-cxznVQro8GI.csv -v ../dataset/EgoOutside/vids/running/Blackpool\ 10k\ fun\ run\ my\ \(pov\)-cxznVQro8GI.mp4 &
./Vid2OpticalFlowCSV/sparse_flow -d /dev/null -c config.xml -o ../dataset/EgoOutside/csvs_32x32/running/My\ 5k\ run\ recorded\ with\ Google\ Glass-kLlQq7uz220.csv -v ../dataset/EgoOutside/vids/running/My\ 5k\ run\ recorded\ with\ Google\ Glass-kLlQq7uz220.mp4 &
./Vid2OpticalFlowCSV/sparse_flow -d /dev/null -c config.xml -o ../dataset/EgoOutside/csvs_32x32/running/Down2Earth\ 5k\ Race\ Oleta\ -\ unedited\ POV\ video\ of\ entire\ course-sZaIfHhiidk.csv -v ../dataset/EgoOutside/vids/running/Down2Earth\ 5k\ Race\ Oleta\ -\ unedited\ POV\ video\ of\ entire\ course-sZaIfHhiidk.mp4 &
./Vid2OpticalFlowCSV/sparse_flow -d /dev/null -c config.xml -o ../dataset/EgoOutside/csvs_32x32/running/7k\ early\ morning\ jog\ in\ Sveitsi\ forest-NMIa46Pr3Ro.csv -v ../dataset/EgoOutside/vids/running/7k\ early\ morning\ jog\ in\ Sveitsi\ forest-NMIa46Pr3Ro.mp4 &
